/**
 * Static assets under /public/images/figma (exported from Figma).
 * Prefer these over remote MCP URLs so builds don’t break when links expire.
 */
export const figmaAssets = {
  vector: "/images/figma/vector.svg",
  rectangle2: "/images/figma/rectangle2.png",
  projectA: "/images/figma/project-a.png",
  projectB: "/images/figma/project-b.png",
  projectC: "/images/figma/project-c.png",
  gallery: "/images/figma/gallery.jpg",
  image5: "/images/figma/image5.png",
  image8: "/images/figma/image8.png",
  figmaTool: "/images/figma/figma-tool.svg",
  illustrator: "/images/figma/illustrator.svg",
  photoshop: "/images/figma/photoshop.svg",
  meta: "/images/figma/meta.svg",
  googleAds: "/images/figma/google-ads.svg",
  framer: "/images/figma/framer.svg",
  vscodeMask: "/images/figma/vscode-mask.svg",
  discordIcon: "/images/figma/discord-icon.svg",
  logoDiPen: "/images/figma/logo-dipen.svg",
  iconSpark: "/images/figma/icon-spark.svg",
  iconArrowBadge: "/images/figma/icon-arrow-badge.svg",
  arrowUp: "/images/figma/arrow-up.svg",
  lineDecor: "/images/figma/line-decor.svg",
  lineDivider: "/images/figma/line-divider.svg",
  client4: "/images/figma/client4.svg",
  client3: "/images/figma/client3.svg",
  client6: "/images/figma/client6.svg",
  client7: "/images/figma/client7.svg",
  arrowSmall: "/images/figma/arrow-small.svg",
  footerArrow: "/images/figma/footer-arrow.svg",
  featuredArrow: "/images/figma/featured-arrow.svg",
} as const;
